package model.bean;
// Generated 31/05/2015 13:50:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Bairro generated by hbm2java
 */
public class Bairro  implements java.io.Serializable {


     private Integer baicod;
     private String bainome;
     private Set enderecos = new HashSet(0);

    public Bairro() {
    }

	
    public Bairro(String bainome) {
        this.bainome = bainome;
    }
    public Bairro(String bainome, Set enderecos) {
       this.bainome = bainome;
       this.enderecos = enderecos;
    }
   
    public Integer getBaicod() {
        return this.baicod;
    }
    
    public void setBaicod(Integer baicod) {
        this.baicod = baicod;
    }
    public String getBainome() {
        return this.bainome;
    }
    
    public void setBainome(String bainome) {
        this.bainome = bainome;
    }
    public Set getEnderecos() {
        return this.enderecos;
    }
    
    public void setEnderecos(Set enderecos) {
        this.enderecos = enderecos;
    }




}


