package model.bean;
// Generated 31/05/2015 13:50:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer clicod;
     private String clinome;
     private long clicpf;
     private String clilogin;
     private String clisenha;
     private String clifone1;
     private String clifone2;
     private String clifone3;
     private Set enderecos = new HashSet(0);
     private Set vendas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String clinome, long clicpf, String clilogin, String clisenha) {
        this.clinome = clinome;
        this.clicpf = clicpf;
        this.clilogin = clilogin;
        this.clisenha = clisenha;
    }
    public Cliente(String clinome, long clicpf, String clilogin, String clisenha, String clifone1, String clifone2, String clifone3, Set enderecos, Set vendas) {
       this.clinome = clinome;
       this.clicpf = clicpf;
       this.clilogin = clilogin;
       this.clisenha = clisenha;
       this.clifone1 = clifone1;
       this.clifone2 = clifone2;
       this.clifone3 = clifone3;
       this.enderecos = enderecos;
       this.vendas = vendas;
    }
   
    public Integer getClicod() {
        return this.clicod;
    }
    
    public void setClicod(Integer clicod) {
        this.clicod = clicod;
    }
    public String getClinome() {
        return this.clinome;
    }
    
    public void setClinome(String clinome) {
        this.clinome = clinome;
    }
    public long getClicpf() {
        return this.clicpf;
    }
    
    public void setClicpf(long clicpf) {
        this.clicpf = clicpf;
    }
    public String getClilogin() {
        return this.clilogin;
    }
    
    public void setClilogin(String clilogin) {
        this.clilogin = clilogin;
    }
    public String getClisenha() {
        return this.clisenha;
    }
    
    public void setClisenha(String clisenha) {
        this.clisenha = clisenha;
    }
    public String getClifone1() {
        return this.clifone1;
    }
    
    public void setClifone1(String clifone1) {
        this.clifone1 = clifone1;
    }
    public String getClifone2() {
        return this.clifone2;
    }
    
    public void setClifone2(String clifone2) {
        this.clifone2 = clifone2;
    }
    public String getClifone3() {
        return this.clifone3;
    }
    
    public void setClifone3(String clifone3) {
        this.clifone3 = clifone3;
    }
    public Set getEnderecos() {
        return this.enderecos;
    }
    
    public void setEnderecos(Set enderecos) {
        this.enderecos = enderecos;
    }
    public Set getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }




}


