package model.bean;
// Generated 31/05/2015 13:50:11 by Hibernate Tools 4.3.1



/**
 * Endereco generated by hbm2java
 */
public class Endereco  implements java.io.Serializable {


     private Integer endcod;
     private Bairro bairro;
     private Cliente cliente;
     private String endrua;
     private int endnumero;
     private int endcep;

    public Endereco() {
    }

    public Endereco(Bairro bairro, Cliente cliente, String endrua, int endnumero, int endcep) {
       this.bairro = bairro;
       this.cliente = cliente;
       this.endrua = endrua;
       this.endnumero = endnumero;
       this.endcep = endcep;
    }
   
    public Integer getEndcod() {
        return this.endcod;
    }
    
    public void setEndcod(Integer endcod) {
        this.endcod = endcod;
    }
    public Bairro getBairro() {
        return this.bairro;
    }
    
    public void setBairro(Bairro bairro) {
        this.bairro = bairro;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getEndrua() {
        return this.endrua;
    }
    
    public void setEndrua(String endrua) {
        this.endrua = endrua;
    }
    public int getEndnumero() {
        return this.endnumero;
    }
    
    public void setEndnumero(int endnumero) {
        this.endnumero = endnumero;
    }
    public int getEndcep() {
        return this.endcep;
    }
    
    public void setEndcep(int endcep) {
        this.endcep = endcep;
    }




}


